### ISSUE TITLE
Setup Order Forms / Registrations forms for Active Campaign

### ISSUE THREAD

**Issue by comfortleaf** [comfortleaf/Legacy-WP#15]
The following forms "when filled out" need "tag" the user with classification, and pass that to active campaign for triggers / actions to happen. (I believe this would be achieved through the API: https://www.activecampaign.com/api/) 
 
-  Anytime a  user purchases a product, it creates a "woocommerce user" which should be tagged with "Customer" in ActiveCampaign. 

- Anytime a user creates an affiliate account, it creates an "affiliate user", which should be tagged with "Affiliate" in ActiveCampaign. 

- Anytime a user creates a wholesale account, it creates an "wholesale user", which should be tagged with "Wholesaler" in ActiveCampaign.

**Comment by jben0324** [comment]
* Anytime a user creates an affiliate account, it creates an "affiliate user", which should be tagged with "Affiliate" in ActiveCampaign.
- This one is done - any user who registers as an affiliate it will be added to active campaign contacts with tag "Affiliate"
