### ISSUE TITLE
Add ?role=regular_customer for PDF

### ISSUE THREAD

**Issue by comfortleaf** [comfortleaf/Legacy-WP#87]
Create we have a ?role=regular_customers for the PDF, which only showing, "Veterans" & "Wholesale Customer" roles. (Regular customers shouldn't see "Sales Representative", and "Affiliate" roles on their PDF.)

Will also need to make the following additions:
- [x] Add "Regular Customer" to the "Account Type" column (Just shows current website price with no discount applied. This is the same as the MSRP / Retail Price...

(Yes this is redundant, but a "regular customer" looking at this chart, may see veterans, and wholesale customers roles, and assume they get those discounts - so we want to make it 100% clear to the user they get 0% discount unless of course, they use coupons etc.) 

- [x] Update the Catalog button on the main shop pages, https://comfortleaf.com/shop/ and https://comfortleaf.com/product-category/natural-cbd-edibles/ (Categories)

- [x] The default PDF, https://comfortleaf.com/wp-content/catalog/catalog shows all the roles. We dont want the general public to see / have access to all this information as some of this is private. So by default, if no "role" is present it should show the "regular_customer" role pricing.

- [x] Add a "all_customers" for the ?roles=all_customers should be displayed to admin, or if i put the ?roles in the url, it should be accessible. (typically only admins will know about the "url role all_customes".

**Comment by jben0324** [comment]
Done and ready for checking
