### ISSUE TITLE
Floating “Shop Now” on mobile

### ISSUE THREAD

**Issue by comfortleaf** [comfortleaf/Legacy-WP#89]
If you look at medterra you will see they have a floating “shop now”, this is something we certainly need to implement through the website, on all pages except for the cart / checkout pages obviously.

<img width="400" alt="screen shot 2018-12-02 at 10 39 40 pm" src="https://user-images.githubusercontent.com/44081118/49351825-31b69c80-f683-11e8-927d-bec96a0aaebd.png">

**Comment by jben0324** [comment]
Done

**Comment by jben0324** [comment]
Done
